### ISSUE TITLE
Failure after clone

### ISSUE THREAD

**Issue by brettwooldridge** [thundergolfer/example-bazel-monorepo#56]
## Description of the problem / feature request:

I cloned the repositoy locally. Then executed ``bazel build //...``. However, the build fails.

### 🐛 Bug Report: Expected Behavior
Successful build.

### 🐛 Bug Report: Actual Behavior
```
INFO: Invocation ID: 7dbc255e-7eeb-4176-a0c1-d5aff91a5ad1
INFO: Repository bazel_gazelle_go_repository_config instantiated at:
  /Users/brettw/Documents/dev/example-bazel-monorepo/WORKSPACE.bazel:40:21: in <toplevel>
  /private/var/tmp/_bazel_brettw/8b843efc2057a180abb205fca8381752/external/bazel_gazelle/deps.bzl:73:25: in gazelle_dependencies
Repository rule go_repository_config defined at:
  /private/var/tmp/_bazel_brettw/8b843efc2057a180abb205fca8381752/external/bazel_gazelle/internal/go_repository_config.bzl:57:39: in <toplevel>
ERROR: An error occurred during the fetch of repository 'bazel_gazelle_go_repository_config':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_brettw/8b843efc2057a180abb205fca8381752/external/bazel_gazelle/internal/go_repository_config.bzl", line 25, column 31, in _go_repository_config_impl
		config_path = ctx.path(ctx.attr.config)
Error in path: Not a regular file: /Users/brettw/Documents/dev/example-bazel-monorepo/WORKSPACE
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_brettw/8b843efc2057a180abb205fca8381752/external/bazel_gazelle/internal/go_repository_config.bzl", line 25, column 31, in _go_repository_config_impl
		config_path = ctx.path(ctx.attr.config)
Error in path: Not a regular file: /Users/brettw/Documents/dev/example-bazel-monorepo/WORKSPACE
ERROR: error loading package '': Encountered error while reading extension file 'buildifier/def.bzl': no such package '@com_github_bazelbuild_buildtools//buildifier': no such package '@bazel_gazelle_go_repository_config//': Not a regular file: /Users/brettw/Documents/dev/example-bazel-monorepo/WORKSPACE
INFO: Elapsed time: 0.128s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
    currently loading: cli ... (6 packages)
    Fetching @py_deps; Restarting.
    Fetching @com_github_bazelbuild_buildtools; Restarting.
    Fetching @graknlabs_bazel_distribution; fetching
```

### 🐛 Bug Report: Steps to Reproduce the Problem

  1. Clone the repo
  2. Execute ``bazel build //...``

### 🐛 Bug Report: Specifications

- Platform: MacOS 11.6.6 (Intel)

**Comment by wbarksdale** [comment]
not sure why this occurs but doing `cp WORKSPACE.bazel WORKSPACE` allowed me to work around
